### ISSUE TITLE
SSAO Prevents Volume Rendering in Managed View

### ISSUE THREAD

**Issue by Sunderlandkyl** [PerkLab/SlicerSandbox#24]
When SSAO is enabled in the latest version of the Lights module (stable or nightly release), volume rendering isn't displayed at all in the 3D views. This is not affected by the "Shadows for volume rendering" option.

Running the following code will reproduce the issue:
````python
lightsLogic = slicer.modules.lights.widgetRepresentation().self().logic
lightsLogic.setUseSSAO(True)
for viewIndex in range(slicer.app.layoutManager().threeDViewCount):
    viewNode = slicer.app.layoutManager().threeDWidget(viewIndex).threeDView().mrmlViewNode()
    lightsLogic.addManagedView(viewNode)
    viewNode.SetOrientationMarkerType(viewNode.OrientationMarkerTypeCube)

import SampleData
mrHead = SampleData.SampleDataLogic().downloadMRHead()
slicer.modules.volumerendering.logic().CreateDefaultVolumeRenderingNodes(mrHead)
````

There also seems to be a rendering issue with the orientation marker when SSAO is enabled. as the frontface of the orientation markers are now culled:
![image](https://github.com/PerkLab/SlicerSandbox/assets/9222709/7432b56f-419e-4877-87b4-26207c698afc) ![image](https://github.com/PerkLab/SlicerSandbox/assets/9222709/809e53f7-b50c-43a7-a084-20e4cec73e6e)

Additionally, if there are multiple 3D views in the current layout that are being managed by the Lights module, then all but one of them will stop rendering. Interacting with the broken views will cause the one working view to become transparent (you can see the window behind Slicer).

![image](https://github.com/PerkLab/SlicerSandbox/assets/9222709/65353585-2a85-4f6b-8cbf-923265318b48)

**Comment by lassoan** [comment]
Thanks for reporting, probably I was too quick to add all that shader code to Lights module. We can revert to the previous version and will revisit this when all the related VTK updates are available and we need to use less custom shader code.

**Comment by Sunderlandkyl** [comment]
I did some more investigating, and I can get volume rendering to show up if I enable volume rendering first, and force the views to render at least once before enabling ssao, though there are still some rendering issues:

```python
import SampleData
mrHead = SampleData.SampleDataLogic().downloadMRHead()
slicer.modules.volumerendering.logic().CreateDefaultVolumeRenderingNodes(mrHead)

slicer.util.forceRenderAllViews()

lightsLogic = slicer.modules.lights.widgetRepresentation().self().logic
lightsLogic.setUseSSAO(True)
for viewIndex in range(slicer.app.layoutManager().threeDViewCount):
    viewNode = slicer.app.layoutManager().threeDWidget(viewIndex).threeDView().mrmlViewNode()
    lightsLogic.addManagedView(viewNode)
    viewNode.SetOrientationMarkerType(viewNode.OrientationMarkerTypeCube)
````

![image](https://github.com/PerkLab/SlicerSandbox/assets/9222709/08ca279f-134c-4eab-9db3-6330c3ada89a)
