### ISSUE TITLE
CombineModels sometimes crashes, vtkbool library needs update to latest version

### ISSUE THREAD

**Issue by mauigna06** [PerkLab/SlicerSandbox#25]
Please see https://github.com/zippy84/vtkbool/issues/72#issuecomment-1883764728

Thanks a lot

**Comment by lassoan** [comment]
@mauigna06 vtkbool is updated to the latest version. Please test.

**Comment by mauigna06** [comment]
Thanks

> Please test

Will do later today

**Comment by mauigna06** [comment]
I cannot check, it appears the new version of this extension was not packaged today :)

**Comment by mauigna06** [comment]
> @mauigna06 vtkbool is updated to the latest version. Please test.

It's solved. Thank you
