### ISSUE TITLE
Unable to build the 3d slicer module

### ISSUE THREAD

**Issue by ujwalk93** [PerkLab/SlicerSandbox#29]
I had built Slicer Sandbox and Slicer github module using make file  and build cmake commands.
But Qt5 is unable to build even though the python modules pyqt5 and slicer are very much installed.
Qt5 is not open source. I need help here. Any other suggestion on how to build the sandbox remove ct table module.

**Comment by lassoan** [comment]
Slicer uses PythonQt for making available Qt in Python. pyqt5 is a conpletely different project,  Slicer does not use it, you do not need it.

Qt5 is open-source and available with permissive LGPL license.

You need to build 3D Slicer first and then you can build this extension. See build instructions at https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/index.html
